<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VTBT3RG" ignored="0" name="SIT" tests="5" failures="1" timestamp="2023-04-16T14:42:36 IST" time="74.128" errors="0">
  <testcase name="FacebookLoginandLogout" time="20.777" classname="Testcase.FacebookLoginandLogout"/>
  <testcase name="FacebookLoginandLogout" time="20.705" classname="Testcase.FacebookLoginandLogout"/>
  <testcase name="FacebookLoginandLogout" time="10.189" classname="Testcase.FacebookLoginandLogout"/>
  <testcase name="FacebookLoginandLogout" time="11.135" classname="Testcase.FacebookLoginandLogout"/>
  <testcase name="FacebookInvalidLogin" time="5.525" classname="Testcase.FacebookLoginandLogout">
    <failure type="java.lang.AssertionError" message="expected [The email address or mobile number you entered isn&amp;apos;t connected to an account. Find your account and log in.] but found [The email address or mobile number you entered isn&amp;apos;t connected to an account. Create a new Facebook account.]">
      <![CDATA[java.lang.AssertionError: expected [The email address or mobile number you entered isn't connected to an account. Find your account and log in.] but found [The email address or mobile number you entered isn't connected to an account. Create a new Facebook account.]
at Testcase.FacebookLoginandLogout.FacebookInvalidLogin(FacebookLoginandLogout.java:98)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- FacebookInvalidLogin -->
</testsuite> <!-- SIT -->
