<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-VTBT3RG" name="Testcase.FacebookLoginandLogout" tests="11" failures="2" timestamp="2023-04-16T14:42:37 IST" time="114.501" errors="1">
  <testcase name="FacebookLoginandLogout" time="20.777" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="8.985" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="13.922" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="20.705" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="TearDown" time="0.165" classname="Testcase.FacebookLoginandLogout">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Testcase.FacebookLoginandLogout.TearDown(FacebookLoginandLogout.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TearDown -->
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="10.189" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="9.112" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="11.135" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookLoginandLogout" time="8.737" classname="Testcase.FacebookLoginandLogout"/>
  <system-out/>
  <testcase name="FacebookInvalidLogin" time="5.525" classname="Testcase.FacebookLoginandLogout">
    <failure type="java.lang.AssertionError" message="expected [The email address or mobile number you entered isn&#039;t connected to an account. Find your account and log in.] but found [The email address or mobile number you entered isn&#039;t connected to an account. Create a new Facebook account.]">
      <![CDATA[java.lang.AssertionError: expected [The email address or mobile number you entered isn't connected to an account. Find your account and log in.] but found [The email address or mobile number you entered isn't connected to an account. Create a new Facebook account.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Testcase.FacebookLoginandLogout.FacebookInvalidLogin(FacebookLoginandLogout.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- FacebookInvalidLogin -->
  <system-out/>
  <testcase name="FacebookInvalidLogin" time="5.249" classname="Testcase.FacebookLoginandLogout">
    <failure type="java.lang.AssertionError" message="expected [The email address or mobile number you entered isn&#039;t connected to an account. Find your account and log in.] but found [The email address or mobile number you entered isn&#039;t connected to an account. Create a new Facebook account.]">
      <![CDATA[java.lang.AssertionError: expected [The email address or mobile number you entered isn't connected to an account. Find your account and log in.] but found [The email address or mobile number you entered isn't connected to an account. Create a new Facebook account.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Testcase.FacebookLoginandLogout.FacebookInvalidLogin(FacebookLoginandLogout.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- FacebookInvalidLogin -->
  <system-out/>
</testsuite> <!-- Testcase.FacebookLoginandLogout -->
